/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import br.com.senactech.NLivrariaDAO.livrariaDAO.livroDAO;
import br.com.senactech.NLivrariaDAO.livrariaDAO.vendaLivroDAO;

/**
 *
 * @author 631701777
 */
public class jfVenda extends javax.swing.JPanel {

    /**
     * Creates new form jfVenda
     */
    public jfVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jppainel = new javax.swing.JPanel();
        jtfidlivro = new javax.swing.JTextField();
        jlidlivro = new javax.swing.JLabel();
        jlqtdvenda = new javax.swing.JLabel();
        jtfqtdvendas = new javax.swing.JTextField();
        jldevolucao = new javax.swing.JLabel();
        jltexto = new javax.swing.JLabel();
        jtfdevolucao = new javax.swing.JTextField();
        jbatualizar = new javax.swing.JButton();

        jlidlivro.setText("Digite a ID do livro:");

        jlqtdvenda.setText("Quantidade vendidas:");

        jldevolucao.setText("Quantidade devoluções:");

        jltexto.setText("Venda/Devolução");

        jbatualizar.setText("Atualizar");
        jbatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbatualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jppainelLayout = new javax.swing.GroupLayout(jppainel);
        jppainel.setLayout(jppainelLayout);
        jppainelLayout.setHorizontalGroup(
            jppainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppainelLayout.createSequentialGroup()
                .addGroup(jppainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jppainelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jppainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jppainelLayout.createSequentialGroup()
                                .addComponent(jldevolucao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfdevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jppainelLayout.createSequentialGroup()
                                .addComponent(jlqtdvenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfqtdvendas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jppainelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jlidlivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jppainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jltexto)
                            .addComponent(jtfidlivro, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jppainelLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jbatualizar)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jppainelLayout.setVerticalGroup(
            jppainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppainelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jltexto)
                .addGap(26, 26, 26)
                .addGroup(jppainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfidlivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlidlivro))
                .addGap(24, 24, 24)
                .addGroup(jppainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlqtdvenda)
                    .addComponent(jtfqtdvendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jppainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jldevolucao)
                    .addComponent(jtfdevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jbatualizar)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jppainel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jppainel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbatualizarActionPerformed
        atualizarEstoque();
    }//GEN-LAST:event_jbatualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbatualizar;
    private javax.swing.JLabel jldevolucao;
    private javax.swing.JLabel jlidlivro;
    private javax.swing.JLabel jlqtdvenda;
    private javax.swing.JLabel jltexto;
    private javax.swing.JPanel jppainel;
    private javax.swing.JTextField jtfdevolucao;
    private javax.swing.JTextField jtfidlivro;
    private javax.swing.JTextField jtfqtdvendas;
    // End of variables declaration//GEN-END:variables
}
